/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tarea10_tatianagarcia;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tatig
 */
public class Principal extends javax.swing.JFrame {

    int xMouse, yMouse;
    Color c;
    public Principal() {
        initComponents();
        Add.setVisible(false);
        Delete.setVisible(false);
        Modify.setVisible(false);
        List.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        Xbutton = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Agregarboton = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ListarBoton = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ModificarBoton = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        EliminarBoton = new javax.swing.JLabel();
        RegistroVehiculardelHacker = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        fondocarro = new javax.swing.JLabel();
        Add = new javax.swing.JPanel();
        loginBtn = new javax.swing.JPanel();
        loginBtnTxt = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Marca = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        Modelo = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        Millas = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        Tipo = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        Camara = new javax.swing.JCheckBox();
        colorboton = new javax.swing.JButton();
        Fecha = new com.toedter.calendar.JCalendar();
        jLabel15 = new javax.swing.JLabel();
        Delete = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_lista2 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        loginBtnTxt4 = new javax.swing.JLabel();
        Modify = new javax.swing.JPanel();
        loginBtn3 = new javax.swing.JPanel();
        loginBtnTxt3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Marca3 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Marca5 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        Tipo2 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        CamaraMod = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        Fecha2 = new com.toedter.calendar.JCalendar();
        jLabel24 = new javax.swing.JLabel();
        CombMod = new javax.swing.JComboBox<>();
        List = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_lista1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(0, 0, 0));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(0, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(0, 255, 255));
        jPanel6.setForeground(new java.awt.Color(0, 0, 0));

        Xbutton.setForeground(new java.awt.Color(0, 0, 0));
        Xbutton.setText("X");
        Xbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Xbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                XbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                XbuttonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(Xbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Xbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(693, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 20));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agregar.png"))); // NOI18N

        Agregarboton.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Agregarboton.setForeground(new java.awt.Color(0, 51, 153));
        Agregarboton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Agregarboton.setText("Agregar");
        Agregarboton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Agregarboton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarbotonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AgregarbotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AgregarbotonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Agregarboton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Agregarboton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 210, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/listar.png"))); // NOI18N

        ListarBoton.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        ListarBoton.setForeground(new java.awt.Color(0, 51, 153));
        ListarBoton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ListarBoton.setText("Listar");
        ListarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListarBotonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ListarBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ListarBotonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ListarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ListarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 210, 40));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modificar.png"))); // NOI18N

        ModificarBoton.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        ModificarBoton.setForeground(new java.awt.Color(0, 51, 153));
        ModificarBoton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ModificarBoton.setText("Modificar");
        ModificarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModificarBotonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ModificarBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ModificarBotonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ModificarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(ModificarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 210, 40));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Eliminar.png"))); // NOI18N

        EliminarBoton.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        EliminarBoton.setForeground(new java.awt.Color(0, 51, 153));
        EliminarBoton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EliminarBoton.setText("Eliminar");
        EliminarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarBotonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EliminarBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EliminarBotonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EliminarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(EliminarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        bg.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 210, 40));

        RegistroVehiculardelHacker.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        RegistroVehiculardelHacker.setForeground(new java.awt.Color(204, 204, 204));
        RegistroVehiculardelHacker.setText("Registro Vehicular ");
        bg.add(RegistroVehiculardelHacker, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 110, 30));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carro.png"))); // NOI18N
        bg.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 110, 110));

        fondocarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen1auto.jpg"))); // NOI18N
        bg.add(fondocarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 500));

        Add.setBackground(new java.awt.Color(0, 51, 102));
        Add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginBtn.setBackground(new java.awt.Color(0, 134, 190));

        loginBtnTxt.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        loginBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        loginBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginBtnTxt.setText("Agregar");
        loginBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout loginBtnLayout = new javax.swing.GroupLayout(loginBtn);
        loginBtn.setLayout(loginBtnLayout);
        loginBtnLayout.setHorizontalGroup(
            loginBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(loginBtnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        loginBtnLayout.setVerticalGroup(
            loginBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(loginBtnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Add.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 80, 30));

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 204));
        jLabel9.setText("Info Vehiculo");
        Add.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 204));
        jLabel10.setText("Marca: ");
        Add.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 80, -1, -1));

        Marca.setBackground(new java.awt.Color(0, 51, 102));
        Marca.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        Marca.setForeground(new java.awt.Color(255, 255, 255));
        Marca.setText("Honda");
        Marca.setBorder(null);
        Marca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MarcaMousePressed(evt);
            }
        });
        Add.add(Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 83, 110, -1));
        Add.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 104, 120, -1));

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 204));
        jLabel11.setText("Modelo:");
        Add.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 135, -1, -1));

        Modelo.setBackground(new java.awt.Color(0, 51, 102));
        Modelo.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        Modelo.setForeground(new java.awt.Color(255, 255, 255));
        Modelo.setText("Civic");
        Modelo.setBorder(null);
        Modelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ModeloMousePressed(evt);
            }
        });
        Add.add(Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 138, 100, -1));
        Add.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 159, 110, -1));

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 204, 204));
        jLabel12.setText("Millas:");
        Add.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 190, -1, -1));

        Millas.setBackground(new java.awt.Color(0, 51, 102));
        Millas.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        Millas.setForeground(new java.awt.Color(255, 255, 255));
        Millas.setText("128");
        Millas.setBorder(null);
        Millas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MillasMousePressed(evt);
            }
        });
        Add.add(Millas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 120, -1));
        Add.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 214, 130, -1));

        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 204, 204));
        jLabel13.setText("Tipo:");
        Add.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        Tipo.setBackground(new java.awt.Color(0, 51, 102));
        Tipo.setForeground(new java.awt.Color(255, 255, 255));
        Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Camion", "Pickup", "Turismo", "" }));
        Add.add(Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 100, -1));

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 204, 204));
        jLabel14.setText("Camara:");
        Add.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 234, -1, -1));

        Camara.setBackground(new java.awt.Color(0, 51, 102));
        Camara.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Camara.setForeground(new java.awt.Color(255, 255, 255));
        Camara.setText("El vehiculo contiene 1 o mas camaras");
        Add.add(Camara, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 236, -1, -1));

        colorboton.setBackground(new java.awt.Color(0, 204, 204));
        colorboton.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        colorboton.setForeground(new java.awt.Color(0, 0, 0));
        colorboton.setText("Color");
        colorboton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorbotonMouseClicked(evt);
            }
        });
        Add.add(colorboton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        Fecha.setDoubleBuffered(false);
        Add.add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 400, 180));

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 204, 204));
        jLabel15.setText("Fecha:");
        Add.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        bg.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 460, 500));

        Delete.setBackground(new java.awt.Color(0, 51, 102));

        tb_lista2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Modelo", "Millas", "Tipo", "Fecha", "Color", "Camara"
            }
        ));
        tb_lista2.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(tb_lista2);

        jLabel17.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 204, 204));
        jLabel17.setText("Eliminar Vehiculo");

        jPanel5.setBackground(new java.awt.Color(102, 153, 255));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        loginBtnTxt4.setBackground(new java.awt.Color(102, 102, 102));
        loginBtnTxt4.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        loginBtnTxt4.setForeground(new java.awt.Color(255, 255, 255));
        loginBtnTxt4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginBtnTxt4.setText("Eliminar");
        loginBtnTxt4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtnTxt4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnTxt4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtnTxt4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtnTxt4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginBtnTxt4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginBtnTxt4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout DeleteLayout = new javax.swing.GroupLayout(Delete);
        Delete.setLayout(DeleteLayout);
        DeleteLayout.setHorizontalGroup(
            DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(DeleteLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DeleteLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        DeleteLayout.setVerticalGroup(
            DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeleteLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 372, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DeleteLayout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(86, Short.MAX_VALUE)))
        );

        bg.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 0, 460, -1));

        Modify.setBackground(new java.awt.Color(0, 51, 102));
        Modify.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginBtn3.setBackground(new java.awt.Color(0, 134, 190));

        loginBtnTxt3.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        loginBtnTxt3.setForeground(new java.awt.Color(255, 255, 255));
        loginBtnTxt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginBtnTxt3.setText("Modificar");
        loginBtnTxt3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtnTxt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnTxt3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtnTxt3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtnTxt3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout loginBtn3Layout = new javax.swing.GroupLayout(loginBtn3);
        loginBtn3.setLayout(loginBtn3Layout);
        loginBtn3Layout.setHorizontalGroup(
            loginBtn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginBtn3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(loginBtnTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        loginBtn3Layout.setVerticalGroup(
            loginBtn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginBtn3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(loginBtnTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Modify.add(loginBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 90, 30));

        jLabel18.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 204, 204));
        jLabel18.setText("Info Vehiculo");
        Modify.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel19.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 204, 204));
        jLabel19.setText("Marca: ");
        Modify.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        Marca3.setBackground(new java.awt.Color(0, 51, 102));
        Marca3.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        Marca3.setForeground(new java.awt.Color(255, 255, 255));
        Marca3.setText("Honda");
        Marca3.setBorder(null);
        Marca3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Marca3MousePressed(evt);
            }
        });
        Modify.add(Marca3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 110, -1));
        Modify.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 120, -1));

        jLabel20.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 204, 204));
        jLabel20.setText("Modelo:");
        Modify.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel21.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 204, 204));
        jLabel21.setText("Millas:");
        Modify.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 190, -1, -1));

        Marca5.setBackground(new java.awt.Color(0, 51, 102));
        Marca5.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        Marca5.setForeground(new java.awt.Color(255, 255, 255));
        Marca5.setText("128");
        Marca5.setBorder(null);
        Marca5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Marca5MousePressed(evt);
            }
        });
        Marca5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Marca5ActionPerformed(evt);
            }
        });
        Modify.add(Marca5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 120, -1));
        Modify.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 214, 130, -1));

        jLabel22.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 204, 204));
        jLabel22.setText("Tipo:");
        Modify.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        Tipo2.setBackground(new java.awt.Color(0, 51, 102));
        Tipo2.setForeground(new java.awt.Color(255, 255, 255));
        Tipo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Camion", "Pickup", "Turismo", " " }));
        Modify.add(Tipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 100, -1));

        jLabel23.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 204, 204));
        jLabel23.setText("Camara:");
        Modify.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 234, -1, -1));

        CamaraMod.setBackground(new java.awt.Color(0, 51, 102));
        CamaraMod.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        CamaraMod.setForeground(new java.awt.Color(255, 255, 255));
        CamaraMod.setText("El vehiculo contiene 1 o mas camaras");
        Modify.add(CamaraMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 236, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Color");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        Modify.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        Fecha2.setDoubleBuffered(false);
        Modify.add(Fecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 400, 180));

        jLabel24.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 204, 204));
        jLabel24.setText("Fecha:");
        Modify.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        CombMod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CombMod.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CombModItemStateChanged(evt);
            }
        });
        Modify.add(CombMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 110, -1));

        bg.add(Modify, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 460, 500));

        List.setBackground(new java.awt.Color(0, 51, 102));
        List.setForeground(new java.awt.Color(0, 51, 153));

        jLabel16.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 204, 204));
        jLabel16.setText("Lista de Vehiculo");

        tb_lista1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Modelo", "Millas", "Tipo", "Fecha", "Color", "Camara"
            }
        ));
        tb_lista1.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(tb_lista1);

        javax.swing.GroupLayout ListLayout = new javax.swing.GroupLayout(List);
        List.setLayout(ListLayout);
        ListLayout.setHorizontalGroup(
            ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(149, 149, 149))
        );
        ListLayout.setVerticalGroup(
            ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        bg.add(List, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 460, -1));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnTxt4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnTxt4MouseClicked
        // TODO add your handling code here:
        if (tb_lista2.getSelectedRow() >= 0) {
            int r = JOptionPane.showConfirmDialog(tb_lista2, "Desea elimnar producto????", "Eliminar producto", YES_NO_OPTION);
            if (r == 0) {
                inventario.remove(tb_lista2.getSelectedRow());
                listarTabla();
                JOptionPane.showMessageDialog(this, "Producto Elimniado exitosamente");

            }

        }
    }//GEN-LAST:event_loginBtnTxt4MouseClicked

    private void loginBtnTxt4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnTxt4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtnTxt4MouseEntered

    private void loginBtnTxt4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnTxt4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtnTxt4MouseExited

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void XbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XbuttonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_XbuttonMouseClicked

    private void XbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XbuttonMouseEntered
        jPanel6.setBackground(Color.red);
        Xbutton.setForeground(Color.white);
    }//GEN-LAST:event_XbuttonMouseEntered

    private void XbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XbuttonMouseExited
        jPanel6.setBackground(Color.white);
        Xbutton.setForeground(Color.black);
    }//GEN-LAST:event_XbuttonMouseExited

    private void AgregarbotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarbotonMouseClicked
        List.setVisible(false);
        Modify.setVisible(false);
        Delete.setVisible(false);
        Add.setVisible(true);
    }//GEN-LAST:event_AgregarbotonMouseClicked

    private void AgregarbotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarbotonMouseEntered
        jPanel1.setBackground(Color.blue);
        Agregarboton.setForeground(Color.white);
    }//GEN-LAST:event_AgregarbotonMouseEntered

    private void AgregarbotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarbotonMouseExited
        jPanel1.setBackground(Color.white);
        Agregarboton.setForeground(Color.black);
    }//GEN-LAST:event_AgregarbotonMouseExited

    private void ListarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListarBotonMouseClicked
        Modify.setVisible(false);
        Delete.setVisible(false);
        Add.setVisible(false);
        List.setVisible(true);

        try {

            //limpiar tabla
            tb_lista1.setModel(new javax.swing.table.DefaultTableModel(
                    new Object[][]{},
                    new String[]{
                        "Marca", "Modelo", "Millas", "Tipo","Fecha","Color","Camara"
                    }
            ));

            // TODO add your handling code here:
            String cc, n, p, u;
            for (Carro t : inventario) {
                Object[] row = {t.getMarca(),t.getModelo(),t.getMillas(),t.getTipo(),t.getFecha(),t.getColor(),t.isCamara()};
                DefaultTableModel modelo = (DefaultTableModel) tb_lista1.getModel();
                modelo.addRow(row);
                tb_lista1.setModel(modelo);            
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_ListarBotonMouseClicked

    private void listarTabla() {
        try {

            //limpiar tabla
            tb_lista2.setModel(new javax.swing.table.DefaultTableModel(
                    new Object[][]{},
                    new String[]{
                        "Marca", "Modelo", "Millas", "Tipo","Fecha","Color","Camara"
                    }
            ));
            // TODO add your handling code here:
            for (Carro t : inventario) {
                Object[] row = {t.getMarca(),t.getModelo(),t.getMillas(),t.getTipo(),t.getFecha(),t.getColor(),t.isCamara()};
                DefaultTableModel modelo = (DefaultTableModel) tb_lista2.getModel();
                modelo.addRow(row);
                tb_lista2.setModel(modelo);            
            }
            

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    private void ListarBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListarBotonMouseEntered
        jPanel2.setBackground(Color.blue);
        ListarBoton.setForeground(Color.white);
    }//GEN-LAST:event_ListarBotonMouseEntered

    private void ListarBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListarBotonMouseExited
        jPanel2.setBackground(Color.white);
        ListarBoton.setForeground(Color.black);
    }//GEN-LAST:event_ListarBotonMouseExited

    private void ModificarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarBotonMouseClicked
        Delete.setVisible(false);
        Add.setVisible(false);
        List.setVisible(false);
        Modify.setVisible(true);

        llenarcombo();
    }//GEN-LAST:event_ModificarBotonMouseClicked

    private void ModificarBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarBotonMouseEntered
        jPanel3.setBackground(Color.blue);
        ModificarBoton.setForeground(Color.white);
    }//GEN-LAST:event_ModificarBotonMouseEntered

    private void ModificarBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarBotonMouseExited
        jPanel3.setBackground(Color.white);
        ModificarBoton.setForeground(Color.black);
    }//GEN-LAST:event_ModificarBotonMouseExited

    private void EliminarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarBotonMouseClicked
        Add.setVisible(false);
        List.setVisible(false);
        Modify.setVisible(false);
        Delete.setVisible(true);

        listarTabla();
    }//GEN-LAST:event_EliminarBotonMouseClicked

    private void EliminarBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarBotonMouseEntered
        jPanel4.setBackground(Color.blue);
        EliminarBoton.setForeground(Color.white);
    }//GEN-LAST:event_EliminarBotonMouseEntered

    private void EliminarBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarBotonMouseExited
        jPanel4.setBackground(Color.white);
        EliminarBoton.setForeground(Color.BLACK);
    }//GEN-LAST:event_EliminarBotonMouseExited

    private void loginBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnTxtMouseClicked
        //guardar data
        try {
            String tipo = Tipo.getSelectedItem().toString();
            
            boolean cam = Camara.isSelected();
            Calendar cal = Fecha.getCalendar();
            
            inventario.add(
                new Carro(Marca.getText(), Modelo.getText(), cal, c,
                        Integer.parseInt(Millas.getText()), tipo, cam)
            );

            Marca.setText("");
            Modelo.setText("");
            Millas.setText("");
            Camara.setSelected(false);
            //tf_unidad.setText("");
            JOptionPane.showMessageDialog(this, "Producto agregado exitosamente");

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_loginBtnTxtMouseClicked

    private void loginBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnTxtMouseEntered
        loginBtn.setBackground(new Color(0, 156, 223));
    }//GEN-LAST:event_loginBtnTxtMouseEntered

    private void loginBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnTxtMouseExited
        loginBtn.setBackground(new Color(0, 134, 190));
    }//GEN-LAST:event_loginBtnTxtMouseExited

    private void loginBtnTxt3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnTxt3MouseClicked
        // TODO add your handling code here:

        inventario.get(
            CombMod.getSelectedIndex()
        ).setMarca(Marca3.getText());

        inventario.get(
            CombMod.getSelectedIndex()
        ).setMillas(Integer.parseInt(Marca5.getText()));

        inventario.get(
            CombMod.getSelectedIndex()
        ).setCamara(CamaraMod.isSelected());
        inventario.get(
            CombMod.getSelectedIndex()
        ).setFecha(Fecha2.getCalendar());
        inventario.get(
            CombMod.getSelectedIndex()
        ).setTipo(Tipo2.getSelectedItem().toString());

        Marca.setText("");
        Modelo.setText("");
        Millas.setText("");
        Camara.setSelected(false);
        JOptionPane.showMessageDialog(this, "Producto Modificado exitosamente");

        llenarcombo();

    }//GEN-LAST:event_loginBtnTxt3MouseClicked

    private void loginBtnTxt3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnTxt3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtnTxt3MouseEntered

    private void loginBtnTxt3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnTxt3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtnTxt3MouseExited

    private void CombModItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CombModItemStateChanged
        if (evt.getStateChange() == 2) {
            Carro t = (Carro) CombMod.getSelectedItem();
            Marca3.setText(t.getMarca());
            Marca5.setText(Integer.toString(t.getMillas()));
            CamaraMod.setSelected(t.isCamara());
            Fecha2.setCalendar(t.getFecha());
                    
            //Falta color, fecha, tipo, camara
        }
    }//GEN-LAST:event_CombModItemStateChanged

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        c = JColorChooser.showDialog(null, "Seleccione color: ", Color.yellow);
    }//GEN-LAST:event_jButton2MouseClicked

    private void colorbotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorbotonMouseClicked
        c = JColorChooser.showDialog(null, "Seleccione color: ", Color.yellow);
    }//GEN-LAST:event_colorbotonMouseClicked

    private void MarcaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MarcaMousePressed
        Marca.setText("");
    }//GEN-LAST:event_MarcaMousePressed

    private void ModeloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModeloMousePressed
        Modelo.setText("");
    }//GEN-LAST:event_ModeloMousePressed

    private void MillasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MillasMousePressed
        Millas.setText("");
    }//GEN-LAST:event_MillasMousePressed

    private void Marca3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Marca3MousePressed
        Marca3.setText("");
    }//GEN-LAST:event_Marca3MousePressed

    private void Marca5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Marca5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Marca5ActionPerformed

    private void Marca5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Marca5MousePressed
        Marca5.setText("");
    }//GEN-LAST:event_Marca5MousePressed

    private void llenarcombo() {
        CombMod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{}));
        for (Carro t : inventario) {
                DefaultComboBoxModel modelo =
                        (DefaultComboBoxModel) CombMod.getModel();
                modelo.addElement(t);
                CombMod.setModel(modelo);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    ArrayList<Carro> inventario=new ArrayList();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Add;
    private javax.swing.JLabel Agregarboton;
    private javax.swing.JCheckBox Camara;
    private javax.swing.JCheckBox CamaraMod;
    private javax.swing.JComboBox<String> CombMod;
    private javax.swing.JPanel Delete;
    private javax.swing.JLabel EliminarBoton;
    private com.toedter.calendar.JCalendar Fecha;
    private com.toedter.calendar.JCalendar Fecha2;
    private javax.swing.JPanel List;
    private javax.swing.JLabel ListarBoton;
    private javax.swing.JTextField Marca;
    private javax.swing.JTextField Marca3;
    private javax.swing.JTextField Marca5;
    private javax.swing.JTextField Millas;
    private javax.swing.JTextField Modelo;
    private javax.swing.JLabel ModificarBoton;
    private javax.swing.JPanel Modify;
    private javax.swing.JLabel RegistroVehiculardelHacker;
    private javax.swing.JComboBox<String> Tipo;
    private javax.swing.JComboBox<String> Tipo2;
    private javax.swing.JLabel Xbutton;
    private javax.swing.JPanel bg;
    private javax.swing.JButton colorboton;
    private javax.swing.JLabel fondocarro;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPanel loginBtn;
    private javax.swing.JPanel loginBtn3;
    private javax.swing.JLabel loginBtnTxt;
    private javax.swing.JLabel loginBtnTxt3;
    private javax.swing.JLabel loginBtnTxt4;
    private javax.swing.JLabel logo;
    private javax.swing.JTable tb_lista1;
    private javax.swing.JTable tb_lista2;
    // End of variables declaration//GEN-END:variables
}
